### ISSUE TITLE
Value error on magic armor

### ISSUE THREAD

**Issue by Jhobean** [cbnolok/SphereX-Scriptpack#53]
If you add c_blacksmith you'll get lot of console error
![image](https://user-images.githubusercontent.com/51728381/99469534-f31e5900-2910-11eb-9b51-1e8a7a1e3ac4.png)

This bug it's because the value of  all item this  BUY list dont have value:
VENDOR_B_MAGIC_ARMOR

By defaut there is no ressource and no value so when doing .xshow value we get 0.

For exemple: 
```
[ITEMDEF i_chainmail_coif_defense]
ID=i_chainmail_coif
NAME=Chainmail Coif of Defense
TEVENTS=ei_equipitem
TEVENTS=ei_magic_preaos

CATEGORY=Provisions - Armor - Magic
SUBSECTION=Chainmail
DESCRIPTION=Chainmail Coif of Defense

ON=@Create
	MOREY=20.0
	ATTR=attr_magic
	HITPOINTS=45
	COLOR=color_magic_defense
```
How to fix?
1- Fix core to get the value of the ID= (in this exemple i_chainmail_coif)
2- Add value= on each?
3- Add ressource to item?

We don't have this problem with weapon because there is a ressource:

```
[ITEMDEF i_hammer_pick_power]
ID=i_hammer_pick
NAME=Hammer Pick of Power
RESOURCES=16 i_ingot_iron, i_hammer_pick
TEVENTS=ei_equipitem
TEVENTS=ei_magic_preaos
```

**Comment by cbnolok** [comment]
I don't know if those were ever craftable or not. How could you get them? Loot? Buying from a vendor? 
I'd add value, if it's meant to be bought or sold (do we have any known values in 51/55 scripts or on uoguide?) or resources (if it's meant to be crafted)

**Comment by Jhobean** [comment]
I just commented these line on script pack. If someone want to be able sell these item, he will need put a value
